#!/usr/bin/env python3
"""Regenerate the "Supported TrueNAS versions" table in README.md.

The table is kernel-keyed. A sysext's kernel modules bind to the exact
kernel string (uname -r / vermagic), and many TrueNAS point releases ship
the same kernel, so one build covers a whole range of versions. Rows come
from two sources:

  * .github/kernel-map.json (maintained by gen-kernel-map.py from the
    rootfs.mtree manifests on download.truenas.com): which TrueNAS versions
    ship which kernel.
  * This repository's published releases (GitHub releases JSON array on
    stdin): which kernels have an installable build, and which release the
    installer serves for them.

A kernel with no release still gets a row (marked "not built yet"), so the
table is a complete coverage map instead of a list of what happens to exist.

Usage (see .github/workflows/update-supported-versions.yml):
    gh api "repos/${GITHUB_REPOSITORY}/releases?per_page=100" \
        | gen-supported-versions.py README.md .github/kernel-map.json
"""
import json
import re
import sys

BEGIN_PREFIX = "<!-- BEGIN supported-versions"
BEGIN_LINE = ("<!-- BEGIN supported-versions (auto-generated by "
              ".github/workflows/update-supported-versions.yml - do not edit by hand) -->")
END_MARK = "<!-- END supported-versions -->"

# Parsed out of the release body that build.yml renders. The header and the
# "Target kernel" row are identical across the sibling sysexts; the driver row
# label differs (Gasket driver / HailoRT driver / MemryX SDK), so match any.
HDR_RE = re.compile(r"for TrueNAS SCALE (.+?) \((.+?)\)")
KER_RE = re.compile(r"Target kernel\s*\|\s*`([^`]+)`")
DRV_RE = re.compile(r"\|\s*(Gasket driver|HailoRT driver|MemryX SDK)\s*\|\s*`([^`]+)`")
# Fallback when a release body is not in the standard format: pull the TrueNAS
# version out of the tag (vX-<drivertoken>...). The version itself may contain
# dashes (26.0.0-BETA.2), so stop at the first known driver token.
TAG_VER_RE = re.compile(r"^v(.+?)-(?:gasket|hailo|hailort|memryx)", re.IGNORECASE)


def truenas_sort_key(version):
    """Order TrueNAS versions: numeric base, then BETA < RC < final, then num."""
    base, _, pre = version.partition("-")
    bp = [int(p) if p.isdigit() else 0 for p in base.split(".")]
    if not pre:
        return (bp, 3, 0)  # a final release sorts above its BETA/RC
    typ, _, num = pre.partition(".")
    rank = {"BETA": 0, "RC": 1}.get(typ.upper(), 2)
    return (bp, rank, int(num) if num.isdigit() else 0)


def is_preview_version(version):
    """A BETA/RC TrueNAS version is the preview channel; matches how install.sh
    classifies the running version (so the table's channel and the installer's
    behaviour can never disagree)."""
    return bool(re.search(r"-(?:BETA|RC)", version, re.IGNORECASE))


def parse_releases(data):
    """GitHub releases JSON array -> {version: [entry, ...]}, drafts skipped."""
    releases_by_version = {}
    for r in data:
        if r.get("draft"):
            continue
        tag = r.get("tag_name", "")
        body = r.get("body") or ""
        hdr = HDR_RE.search(body)
        if hdr:
            version, train = hdr.group(1).strip(), hdr.group(2).strip()
        else:
            tm = TAG_VER_RE.match(tag)
            if not tm:
                continue  # cannot identify the TrueNAS version; skip it
            version, train = tm.group(1), ""
        ker = KER_RE.search(body)
        drv = DRV_RE.search(body)
        releases_by_version.setdefault(version, []).append({
            "version": version,
            "train": train,
            "kver": ker.group(1) if ker else "",
            # "Gasket driver" -> "Gasket 1.0-18.4"; "MemryX SDK" -> "MemryX SDK 2.1"
            "driver": f"{drv.group(1).replace(' driver', '')} {drv.group(2)}" if drv else "",
            "prerelease": bool(r.get("prerelease")),
            "tag": tag,
            "url": r.get("html_url", ""),
            "published": r.get("published_at") or r.get("created_at") or "",
        })
    return releases_by_version


def served_releases(releases_by_version):
    """The one release install.sh serves per version:
      * Preview (BETA/RC) versions -> newest release (prereleases allowed).
      * Stable versions -> newest PROMOTED (non-prerelease) release. An
        unverified prerelease-only stable build is not auto-installable (it is
        gated behind hardware-test promotion), so it is omitted until then."""
    stable, preview = {}, {}
    for version, rels in releases_by_version.items():
        rels.sort(key=lambda x: x["published"], reverse=True)
        if is_preview_version(version):
            preview[version] = rels[0]
        else:
            promoted = [x for x in rels if not x["prerelease"]]
            if promoted:
                stable[version] = promoted[0]
    return stable, preview


def version_range(versions):
    vs = sorted(versions, key=truenas_sort_key)
    return vs[0] if len(vs) == 1 else f"{vs[0]} - {vs[-1]}"


def build_rows(stable, preview, kernel_map):
    """One row per known stable kernel (built or not), then stable releases
    the map does not know (single-version rows), then preview releases."""
    by_kernel = {}
    mapped_versions = set()
    for train_versions in (kernel_map.get("trains") or {}).values():
        for version, kver in train_versions.items():
            by_kernel.setdefault(kver, []).append(version)
            mapped_versions.add(version)

    keyed = []
    for kver, versions in by_kernel.items():
        rels = []
        for v in versions:
            r = stable.get(v)
            if not r:
                continue
            if r["kver"] and r["kver"] != kver:
                print(f"WARNING: release {r['tag']} records kernel {r['kver']} "
                      f"but the kernel map says {kver} for {v}", file=sys.stderr)
            rels.append(r)
        rels.sort(key=lambda x: x["published"], reverse=True)
        r = rels[0] if rels else None
        keyed.append((max(truenas_sort_key(v) for v in versions), {
            "channel": "Stable", "kver": kver,
            "versions": version_range(versions),
            "driver": r["driver"] if r else "",
            "tag": r["tag"] if r else "",
            "url": r["url"] if r else ""}))

    # A served release for a version the map does not know (older train, or a
    # listing gap) keeps its own single-version row so it never drops off.
    for version, r in stable.items():
        if version in mapped_versions:
            continue
        keyed.append((truenas_sort_key(version), {
            "channel": "Stable", "kver": r["kver"], "versions": version,
            "driver": r["driver"], "tag": r["tag"], "url": r["url"]}))

    keyed.sort(key=lambda t: t[0], reverse=True)
    rows = [row for _, row in keyed]

    for version in sorted(preview, key=truenas_sort_key, reverse=True):
        r = preview[version]
        rows.append({"channel": "Preview (beta)", "kver": r["kver"],
                     "versions": version, "driver": r["driver"],
                     "tag": r["tag"], "url": r["url"]})
    return rows


def render_table(rows):
    lines = ["| Channel | Kernel | TrueNAS versions | Driver | Release |",
             "| --- | --- | --- | --- | --- |"]
    if not rows:
        lines.append("| _none_ | — | _no data yet_ | — | — |")
    for row in rows:
        ker = f"`{row['kver']}`" if row["kver"] else "—"
        if row["url"]:
            rel = f"[`{row['tag']}`]({row['url']})"
        elif row["tag"]:
            rel = f"`{row['tag']}`"
        else:
            rel = "_not built yet_"
        drv = row["driver"] or "—"
        lines.append(f"| {row['channel']} | {ker} | {row['versions']} | {drv} | {rel} |")
    return lines


def main():
    if len(sys.argv) not in (2, 3):
        print("usage: gen-supported-versions.py <README.md> [kernel-map.json]",
              file=sys.stderr)
        sys.exit(2)
    readme_path = sys.argv[1]

    kernel_map = {}
    if len(sys.argv) == 3:
        try:
            with open(sys.argv[2], encoding="utf-8") as f:
                kernel_map = json.load(f)
        except FileNotFoundError:
            print(f"WARNING: {sys.argv[2]} not found; table lists released "
                  "versions only", file=sys.stderr)

    data = json.load(sys.stdin)
    if isinstance(data, dict):  # an API error object, not a list
        print(f"ERROR: GitHub API returned: {data.get('message', data)!r}",
              file=sys.stderr)
        sys.exit(1)
    if len(data) >= 100:
        # per_page=100 without pagination; surface possible truncation loudly
        # rather than silently dropping older releases from the table.
        print("WARNING: 100 releases returned; table may be truncated. Add pagination.",
              file=sys.stderr)

    stable, preview = served_releases(parse_releases(data))
    rows = build_rows(stable, preview, kernel_map)
    table = render_table(rows)

    block = BEGIN_LINE + "\n" + "\n".join(table) + "\n" + END_MARK

    text = open(readme_path, encoding="utf-8").read()
    start = text.find(BEGIN_PREFIX)
    end = text.find(END_MARK)
    if start == -1 or end == -1:
        print(f"ERROR: supported-versions markers not found in {readme_path}",
              file=sys.stderr)
        sys.exit(1)
    end += len(END_MARK)
    new = text[:start] + block + text[end:]
    if new != text:
        open(readme_path, "w", encoding="utf-8").write(new)
        print(f"{readme_path}: supported-versions table updated ({len(rows)} rows)")
    else:
        print(f"{readme_path}: supported-versions table unchanged")


if __name__ == "__main__":
    main()
